---
- name: delete old working directory
  file:
    path: "/tmp/encheres-publiques"
    state: absent
  changed_when: false

- name: create working directory
  file:
    path: "/tmp/encheres-publiques"
    state: directory
  changed_when: false

- name: clone git repo
  git:
    repo: "https://github.com/radium226/encheres-publiques.git"
    version: "archlinux-package"
    dest: "/tmp/encheres-publiques"

- name: make package
  shell: |
    cd "/tmp/encheres-publiques"
    makepkg \
      --force \
      --syncdeps \
      --skipchecksums \
      --noconfirm \
      --clean \
      --cleanbuild

- name: install package
  shell: |
    find "/tmp/encheres-publiques" -name "*.tar.xz" | xargs -I {} yay -U "{}" --noconfirm
